version: 2.1
aliases:
  - defaults: &defaults
      executor:
        name: node/default
        tag: '14.15'
      working_directory: ~/code
  - repo-cache: &repo-cache
      key: v1-app-goodchat-{{ .Environment.CIRCLE_SHA1 }}
  - npm-cache: &npm-cache
      key: v1-app-goodchat-dependencies-{{ checksum "package-lock.json" }}
orbs:
  node: circleci/node@4.1.0
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - save_cache:
          <<: *repo-cache
          paths:
            - ~/code

  package_dependencies:
    <<: *defaults
    steps:
      - restore_cache: *repo-cache
      - run: npm install
      - save-cache:
          <<: *npm-cache
          paths:
            - node_modules
            - ~/.npm
  test:
    <<: *defaults
    steps:
      - run:
          command: npm test
          environment:
            CI: true

workflows:
  test_and_deploy:
    jobs:
      - checkout_code
      - package_dependencies:
          requires:
            - checkout_code
      - test:
          requires:
            - package_dependencies

